# Generated by Django 4.2.16 on 2024-11-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/Profile-pic_dxmgt2', upload_to='images/'),
        ),
    ]
