# Generated by Django 4.2.16 on 2024-11-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/default-profile.jpg', upload_to='profile_images/'),
        ),
    ]
