# Generated by Django 4.2.16 on 2024-11-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_status',
            field=models.BooleanField(default=False),
        ),
    ]
