# Generated by Django 4.2.16 on 2024-11-08 13:19

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_fix_orphaned_milestones'),  # Update with your latest migration
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE comments_comment SET milestone_id = 6 WHERE milestone_id = 4;",
            reverse_sql="UPDATE comments_comment SET milestone_id = 4 WHERE milestone_id = 6;"
        ),
    ]
