# Generated by Django 4.2.16 on 2024-11-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_rename_description_milestone_content'),
        ('comments', '0005_auto_20241108_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='milestones.milestone'),
        ),
    ]
