# Generated by Django 4.2.16 on 2024-11-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_rename_description_milestone_content'),
        ('likes', '0003_alter_like_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='milestones.milestone'),
        ),
    ]
