# Generated by Django 4.2.16 on 2024-11-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='description',
        ),
        migrations.AddField(
            model_name='milestone',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
