# Generated by Django 4.2.16 on 2024-11-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_remove_milestone_description_milestone_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='content',
            new_name='description',
        ),
    ]
