# Generated by Django 4.2.16 on 2024-11-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_rename_content_milestone_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='description',
            new_name='content',
        ),
    ]
