# Generated by Django 4.2.16 on 2024-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_rename_description_milestone_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='milestone_category',
            field=models.CharField(choices=[('physical', 'Physical'), ('cognitive', 'Cognitive'), ('emotional', 'Emotional'), ('social', 'Social'), ('language', 'Language'), ('other', 'Other')], default='other', help_text='Category of the milestone', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
