# Generated by Django 4.2.16 on 2024-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0007_alter_milestone_milestone_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
