# Generated by Django 4.2.16 on 2024-11-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0008_alter_milestone_milestone_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone_category',
            field=models.CharField(choices=[('physical', 'Physical'), ('cognitive', 'Cognitive'), ('emotional', 'Emotional'), ('social', 'Social'), ('motor', 'Motor'), ('language', 'Language'), ('other', 'Other')], default='physical', help_text='Category of the milestone', max_length=20),
        ),
    ]
