# Generated by Django 4.2.16 on 2024-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created_at'], 'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('owner', 'followed'), name='unique_follower'),
        ),
    ]
