# Generated by Django 4.2.16 on 2024-11-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followrequests', '0002_alter_followrequest_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
